"""Template-based code generation for performance optimizations.

Generates real, compilable optimization code for Go, Python, Rust, and
TypeScript.  Instead of emitting recommendations like "add retry wrappers",
this module produces the actual source code ready for insertion.
"""
from __future__ import annotations

from typing import Optional

from ..models import ServiceBlueprint, Finding, LLMCall


# ---------------------------------------------------------------------------
# Go templates
# ---------------------------------------------------------------------------

GO_RETRY = '''\
// retryHTTP wraps an HTTP call with exponential backoff retry.
// Generated by architect-sim for {service_name}.
func retryHTTP(ctx context.Context, client *http.Client, req *http.Request, maxAttempts int) (*http.Response, error) {{
\tvar resp *http.Response
\tvar err error
\tdelay := 200 * time.Millisecond
\tfor attempt := 0; attempt < maxAttempts; attempt++ {{
\t\tif attempt > 0 {{
\t\t\tselect {{
\t\t\tcase <-ctx.Done():
\t\t\t\treturn nil, ctx.Err()
\t\t\tcase <-time.After(delay):
\t\t\t}}
\t\t\tdelay *= 2
\t\t\tif delay > 5*time.Second {{
\t\t\t\tdelay = 5 * time.Second
\t\t\t}}
\t\t}}
\t\tresp, err = client.Do(req.Clone(ctx))
\t\tif err == nil && resp.StatusCode < 500 {{
\t\t\treturn resp, nil
\t\t}}
\t\tif resp != nil {{
\t\t\tresp.Body.Close()
\t\t}}
\t}}
\treturn resp, fmt.Errorf("failed after %d attempts: %w", maxAttempts, err)
}}
'''

GO_CIRCUIT_BREAKER = '''\
// CircuitBreaker prevents cascading failures.
// Generated by architect-sim for {service_name}.
type CircuitBreaker struct {{
\tmu           sync.Mutex
\tfailures     int
\tthreshold    int
\tstate        string // "closed", "open", "half-open"
\tlastFailure  time.Time
\tresetTimeout time.Duration
}}

func NewCircuitBreaker(threshold int, resetTimeout time.Duration) *CircuitBreaker {{
\treturn &CircuitBreaker{{threshold: threshold, resetTimeout: resetTimeout, state: "closed"}}
}}

func (cb *CircuitBreaker) Call(fn func() error) error {{
\tcb.mu.Lock()
\tif cb.state == "open" {{
\t\tif time.Since(cb.lastFailure) > cb.resetTimeout {{
\t\t\tcb.state = "half-open"
\t\t}} else {{
\t\t\tcb.mu.Unlock()
\t\t\treturn fmt.Errorf("circuit breaker open")
\t\t}}
\t}}
\tcb.mu.Unlock()

\terr := fn()

\tcb.mu.Lock()
\tdefer cb.mu.Unlock()
\tif err != nil {{
\t\tcb.failures++
\t\tcb.lastFailure = time.Now()
\t\tif cb.failures >= cb.threshold {{
\t\t\tcb.state = "open"
\t\t}}
\t\treturn err
\t}}
\tcb.failures = 0
\tcb.state = "closed"
\treturn nil
}}
'''

GO_CONNECTION_POOL = '''\
// httpPool is a pre-configured HTTP client with connection pooling.
// Generated by architect-sim for {service_name}.
var httpPool = &http.Client{{
\tTimeout: 30 * time.Second,
\tTransport: &http.Transport{{
\t\tMaxIdleConns:        100,
\t\tMaxIdleConnsPerHost: 10,
\t\tIdleConnTimeout:     90 * time.Second,
\t\tDisableKeepAlives:   false,
\t}},
}}
'''

GO_RESPONSE_CACHE = '''\
// ResponseCache is a TTL-based in-memory cache for HTTP responses.
// Generated by architect-sim for {service_name}.
type ResponseCache struct {{
\tmu      sync.RWMutex
\tentries map[string]*cacheEntry
\tttl     time.Duration
}}

type cacheEntry struct {{
\tdata      []byte
\texpiresAt time.Time
}}

func NewResponseCache(ttl time.Duration) *ResponseCache {{
\treturn &ResponseCache{{entries: make(map[string]*cacheEntry), ttl: ttl}}
}}

func (c *ResponseCache) Get(key string) ([]byte, bool) {{
\tc.mu.RLock()
\tdefer c.mu.RUnlock()
\tentry, ok := c.entries[key]
\tif !ok || time.Now().After(entry.expiresAt) {{
\t\treturn nil, false
\t}}
\treturn entry.data, true
}}

func (c *ResponseCache) Set(key string, data []byte) {{
\tc.mu.Lock()
\tdefer c.mu.Unlock()
\tc.entries[key] = &cacheEntry{{data: data, expiresAt: time.Now().Add(c.ttl)}}
}}
'''

GO_TIMEOUT = '''\
// withTimeout wraps an HTTP request with a context timeout.
// Generated by architect-sim for {service_name}.
func withTimeout(client *http.Client, req *http.Request, timeout time.Duration) (*http.Response, error) {{
\tctx, cancel := context.WithTimeout(req.Context(), timeout)
\tdefer cancel()
\treturn client.Do(req.WithContext(ctx))
}}
'''

# ---------------------------------------------------------------------------
# Python templates
# ---------------------------------------------------------------------------

PY_RETRY = '''\
# Retry wrapper with exponential backoff.
# Generated by architect-sim for {service_name}.
import time
import httpx


def retry_request(
    method: str, url: str, max_attempts: int = 3, **kwargs
) -> httpx.Response:
    """Execute an HTTP request with exponential backoff retry."""
    delay = 0.2
    last_error: Exception | None = None
    for attempt in range(max_attempts):
        if attempt > 0:
            time.sleep(delay)
            delay = min(delay * 2, 5.0)
        try:
            resp = httpx.request(method, url, timeout=30.0, **kwargs)
            if resp.status_code < 500:
                return resp
        except httpx.RequestError as exc:
            last_error = exc
    raise last_error or Exception(f"Failed after {{max_attempts}} attempts")
'''

PY_CIRCUIT_BREAKER = '''\
# Circuit breaker to prevent cascading failures.
# Generated by architect-sim for {service_name}.
import threading
import time
from typing import Callable, TypeVar

T = TypeVar("T")


class CircuitBreaker:
    """Simple circuit breaker: closed -> open -> half-open -> closed."""

    def __init__(self, threshold: int = 5, reset_timeout: float = 30.0) -> None:
        self._lock = threading.Lock()
        self._failures = 0
        self._threshold = threshold
        self._state = "closed"
        self._last_failure = 0.0
        self._reset_timeout = reset_timeout

    def call(self, fn: Callable[[], T]) -> T:
        with self._lock:
            if self._state == "open":
                if time.monotonic() - self._last_failure > self._reset_timeout:
                    self._state = "half-open"
                else:
                    raise RuntimeError("circuit breaker open")

        try:
            result = fn()
        except Exception:
            with self._lock:
                self._failures += 1
                self._last_failure = time.monotonic()
                if self._failures >= self._threshold:
                    self._state = "open"
            raise

        with self._lock:
            self._failures = 0
            self._state = "closed"
        return result
'''

PY_CONNECTION_POOL = '''\
# Connection pool for inter-service calls.
# Generated by architect-sim for {service_name}.
import httpx

_pool = httpx.Client(
    timeout=30.0,
    limits=httpx.Limits(max_connections=100, max_keepalive_connections=20),
    http2=True,
)
'''

PY_RESPONSE_CACHE = '''\
# TTL-based in-memory response cache.
# Generated by architect-sim for {service_name}.
import threading
import time
from typing import Any


class ResponseCache:
    """Thread-safe TTL cache for HTTP responses."""

    def __init__(self, ttl: float = 60.0) -> None:
        self._lock = threading.Lock()
        self._entries: dict[str, tuple[Any, float]] = {{}}
        self._ttl = ttl

    def get(self, key: str) -> Any | None:
        with self._lock:
            entry = self._entries.get(key)
            if entry is None or time.monotonic() > entry[1]:
                return None
            return entry[0]

    def set(self, key: str, value: Any) -> None:
        with self._lock:
            self._entries[key] = (value, time.monotonic() + self._ttl)
'''

PY_TIMEOUT = '''\
# Timeout wrapper for HTTP requests.
# Generated by architect-sim for {service_name}.
import httpx


def request_with_timeout(
    method: str, url: str, timeout: float = 10.0, **kwargs
) -> httpx.Response:
    """Execute an HTTP request with an explicit timeout."""
    return httpx.request(method, url, timeout=timeout, **kwargs)
'''

# ---------------------------------------------------------------------------
# TypeScript templates
# ---------------------------------------------------------------------------

TS_RETRY = '''\
// Retry wrapper with exponential backoff.
// Generated by architect-sim for {service_name}.
async function retryFetch(
  url: string,
  options: RequestInit = {{}},
  maxAttempts = 3,
): Promise<Response> {{
  let delay = 200;
  let lastError: Error | null = null;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {{
    if (attempt > 0) {{
      await new Promise((r) => setTimeout(r, delay));
      delay = Math.min(delay * 2, 5000);
    }}
    try {{
      const resp = await fetch(url, {{
        ...options,
        signal: AbortSignal.timeout(30000),
      }});
      if (resp.status < 500) return resp;
    }} catch (e) {{
      lastError = e as Error;
    }}
  }}
  throw lastError ?? new Error(`Failed after ${{maxAttempts}} attempts`);
}}
'''

TS_CIRCUIT_BREAKER = '''\
// Circuit breaker to prevent cascading failures.
// Generated by architect-sim for {service_name}.
class CircuitBreaker {{
  private failures = 0;
  private state: "closed" | "open" | "half-open" = "closed";
  private lastFailure = 0;

  constructor(
    private threshold = 5,
    private resetTimeoutMs = 30000,
  ) {{}}

  async call<T>(fn: () => Promise<T>): Promise<T> {{
    if (this.state === "open") {{
      if (Date.now() - this.lastFailure > this.resetTimeoutMs) {{
        this.state = "half-open";
      }} else {{
        throw new Error("circuit breaker open");
      }}
    }}
    try {{
      const result = await fn();
      this.failures = 0;
      this.state = "closed";
      return result;
    }} catch (e) {{
      this.failures++;
      this.lastFailure = Date.now();
      if (this.failures >= this.threshold) {{
        this.state = "open";
      }}
      throw e;
    }}
  }}
}}
'''

TS_CONNECTION_POOL = '''\
// Connection pool configuration (Node.js undici agent).
// Generated by architect-sim for {service_name}.
import {{ Agent, setGlobalDispatcher }} from "undici";

const poolAgent = new Agent({{
  keepAliveTimeout: 90_000,
  keepAliveMaxTimeout: 300_000,
  connections: 100,
  pipelining: 1,
}});
setGlobalDispatcher(poolAgent);
'''

TS_RESPONSE_CACHE = '''\
// TTL-based in-memory response cache.
// Generated by architect-sim for {service_name}.
class ResponseCache {{
  private entries = new Map<string, {{ data: unknown; expiresAt: number }}>()

  constructor(private ttlMs: number = 60000) {{}}

  get(key: string): unknown | undefined {{
    const entry = this.entries.get(key);
    if (!entry || Date.now() > entry.expiresAt) {{
      this.entries.delete(key);
      return undefined;
    }}
    return entry.data;
  }}

  set(key: string, data: unknown): void {{
    this.entries.set(key, {{ data, expiresAt: Date.now() + this.ttlMs }});
  }}
}}
'''

TS_TIMEOUT = '''\
// Timeout wrapper for fetch requests.
// Generated by architect-sim for {service_name}.
async function fetchWithTimeout(
  url: string,
  options: RequestInit = {{}},
  timeoutMs = 10000,
): Promise<Response> {{
  return fetch(url, {{
    ...options,
    signal: AbortSignal.timeout(timeoutMs),
  }});
}}
'''

# ---------------------------------------------------------------------------
# Rust templates
# ---------------------------------------------------------------------------

RUST_RETRY = '''\
// Retry wrapper with exponential backoff.
// Generated by architect-sim for {service_name}.
async fn retry_request(
    client: &reqwest::Client,
    req: reqwest::Request,
    max_attempts: u32,
) -> Result<reqwest::Response, reqwest::Error> {{
    let mut delay = std::time::Duration::from_millis(200);
    let mut last_err = None;
    for attempt in 0..max_attempts {{
        if attempt > 0 {{
            tokio::time::sleep(delay).await;
            delay = std::cmp::min(delay * 2, std::time::Duration::from_secs(5));
        }}
        match client.execute(req.try_clone().unwrap()).await {{
            Ok(resp) if resp.status().as_u16() < 500 => return Ok(resp),
            Ok(_) => {{}},
            Err(e) => last_err = Some(e),
        }}
    }}
    Err(last_err.unwrap())
}}
'''

RUST_CIRCUIT_BREAKER = '''\
// Circuit breaker to prevent cascading failures.
// Generated by architect-sim for {service_name}.
use std::sync::Mutex;
use std::time::{{Duration, Instant}};

struct CircuitBreaker {{
    failures: Mutex<CircuitState>,
    threshold: u32,
    reset_timeout: Duration,
}}

struct CircuitState {{
    count: u32,
    state: BreakerState,
    last_failure: Option<Instant>,
}}

#[derive(PartialEq)]
enum BreakerState {{
    Closed,
    Open,
    HalfOpen,
}}

impl CircuitBreaker {{
    fn new(threshold: u32, reset_timeout: Duration) -> Self {{
        Self {{
            failures: Mutex::new(CircuitState {{
                count: 0,
                state: BreakerState::Closed,
                last_failure: None,
            }}),
            threshold,
            reset_timeout,
        }}
    }}

    fn call<F, T, E>(&self, f: F) -> Result<T, E>
    where
        F: FnOnce() -> Result<T, E>,
        E: From<std::io::Error>,
    {{
        {{
            let mut s = self.failures.lock().unwrap();
            if s.state == BreakerState::Open {{
                if s.last_failure.map_or(false, |t| t.elapsed() > self.reset_timeout) {{
                    s.state = BreakerState::HalfOpen;
                }} else {{
                    return Err(E::from(std::io::Error::new(
                        std::io::ErrorKind::ConnectionRefused,
                        "circuit breaker open",
                    )));
                }}
            }}
        }}
        match f() {{
            Ok(val) => {{
                let mut s = self.failures.lock().unwrap();
                s.count = 0;
                s.state = BreakerState::Closed;
                Ok(val)
            }}
            Err(e) => {{
                let mut s = self.failures.lock().unwrap();
                s.count += 1;
                s.last_failure = Some(Instant::now());
                if s.count >= self.threshold {{
                    s.state = BreakerState::Open;
                }}
                Err(e)
            }}
        }}
    }}
}}
'''

RUST_CONNECTION_POOL = '''\
// HTTP client with connection pooling.
// Generated by architect-sim for {service_name}.
use std::time::Duration;

fn build_pooled_client() -> reqwest::Client {{
    reqwest::Client::builder()
        .pool_max_idle_per_host(10)
        .pool_idle_timeout(Duration::from_secs(90))
        .timeout(Duration::from_secs(30))
        .build()
        .expect("failed to build HTTP client")
}}
'''

RUST_RESPONSE_CACHE = '''\
// TTL-based in-memory response cache.
// Generated by architect-sim for {service_name}.
use std::collections::HashMap;
use std::sync::RwLock;
use std::time::{{Duration, Instant}};

struct ResponseCache {{
    entries: RwLock<HashMap<String, CacheEntry>>,
    ttl: Duration,
}}

struct CacheEntry {{
    data: Vec<u8>,
    expires_at: Instant,
}}

impl ResponseCache {{
    fn new(ttl: Duration) -> Self {{
        Self {{
            entries: RwLock::new(HashMap::new()),
            ttl,
        }}
    }}

    fn get(&self, key: &str) -> Option<Vec<u8>> {{
        let entries = self.entries.read().unwrap();
        match entries.get(key) {{
            Some(entry) if Instant::now() < entry.expires_at => Some(entry.data.clone()),
            _ => None,
        }}
    }}

    fn set(&self, key: String, data: Vec<u8>) {{
        let mut entries = self.entries.write().unwrap();
        entries.insert(
            key,
            CacheEntry {{
                data,
                expires_at: Instant::now() + self.ttl,
            }},
        );
    }}
}}
'''

RUST_TIMEOUT = '''\
// Timeout wrapper for HTTP requests.
// Generated by architect-sim for {service_name}.
async fn request_with_timeout(
    client: &reqwest::Client,
    req: reqwest::Request,
    timeout: std::time::Duration,
) -> Result<reqwest::Response, reqwest::Error> {{
    let client = client
        .clone();  // cheap Arc clone
    tokio::time::timeout(timeout, client.execute(req))
        .await
        .map_err(|_| {{
            // Convert tokio timeout into a reqwest-compatible error by
            // building a request that is guaranteed to fail immediately.
            reqwest::get("http://[::0]:0")  // never resolves
        }})
        .and_then(|r| r)
}}
'''

# ---------------------------------------------------------------------------
# Template registry
# ---------------------------------------------------------------------------

TEMPLATES: dict[str, dict[str, str]] = {
    "retry": {
        "go": GO_RETRY,
        "python": PY_RETRY,
        "node": TS_RETRY,
        "rust": RUST_RETRY,
    },
    "circuit_breaker": {
        "go": GO_CIRCUIT_BREAKER,
        "python": PY_CIRCUIT_BREAKER,
        "node": TS_CIRCUIT_BREAKER,
        "rust": RUST_CIRCUIT_BREAKER,
    },
    "connection_pool": {
        "go": GO_CONNECTION_POOL,
        "python": PY_CONNECTION_POOL,
        "node": TS_CONNECTION_POOL,
        "rust": RUST_CONNECTION_POOL,
    },
    "response_cache": {
        "go": GO_RESPONSE_CACHE,
        "python": PY_RESPONSE_CACHE,
        "node": TS_RESPONSE_CACHE,
        "rust": RUST_RESPONSE_CACHE,
    },
    "timeout": {
        "go": GO_TIMEOUT,
        "python": PY_TIMEOUT,
        "node": TS_TIMEOUT,
        "rust": RUST_TIMEOUT,
    },
}

# Map common language variants to canonical keys used in TEMPLATES.
_LANG_ALIASES: dict[str, str] = {
    "go": "go",
    "golang": "go",
    "python": "python",
    "py": "python",
    "node": "node",
    "typescript": "node",
    "ts": "node",
    "javascript": "node",
    "js": "node",
    "rust": "rust",
    "rs": "rust",
}

OPTIMIZATION_TYPES = list(TEMPLATES.keys())
SUPPORTED_LANGUAGES = ["go", "python", "node", "rust"]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_optimization_code(
    optimization_type: str,
    language: str,
    service_name: str = "",
    **kwargs,
) -> str:
    """Generate optimization code for a specific language.

    Args:
        optimization_type: One of ``OPTIMIZATION_TYPES``.
        language: One of ``SUPPORTED_LANGUAGES`` (aliases accepted).
        service_name: Inserted into the generated comment header.

    Returns:
        Ready-to-use source code string.

    Raises:
        ValueError: If *optimization_type* or *language* is unknown.
    """
    lang = _LANG_ALIASES.get(language.lower())
    if lang is None:
        raise ValueError(
            f"Unsupported language {language!r}. "
            f"Choose from: {', '.join(sorted(_LANG_ALIASES))}"
        )

    templates = TEMPLATES.get(optimization_type)
    if templates is None:
        raise ValueError(
            f"Unknown optimization type {optimization_type!r}. "
            f"Choose from: {', '.join(OPTIMIZATION_TYPES)}"
        )

    template = templates.get(lang)
    if template is None:
        raise ValueError(
            f"No {optimization_type!r} template for language {lang!r}"
        )

    return template.format(service_name=service_name or "unknown")


def generate_optimizations_for_service(
    bp: ServiceBlueprint,
    findings: list[Finding],
    llm_calls: Optional[list[LLMCall]] = None,
) -> list[tuple[str, str, str]]:
    """Generate all applicable optimization code for a service.

    Inspects *findings* and the blueprint to decide which optimizations to
    emit:

    * Resilience score below 30 pct  ->  retry wrapper + circuit breaker
    * Outbound calls without timeout  ->  timeout wrapper
    * Repeated identical outbound calls  ->  response cache
    * Raw ``http.Client`` / ``httpx`` without pool configuration  ->
      connection pool

    Returns:
        List of ``(optimization_type, code, description)`` tuples.
    """
    lang = _LANG_ALIASES.get(bp.language.lower(), bp.language.lower())
    if lang not in SUPPORTED_LANGUAGES:
        return []

    results: list[tuple[str, str, str]] = []

    # Categorize findings for this service.
    has_timeout_issue = False
    has_low_resilience = False
    seen_paths: dict[str, int] = {}  # path -> count of outbound calls

    for f in findings:
        if f.service != bp.name:
            continue
        if f.finding_type == "timeout_issue":
            has_timeout_issue = True
        if "resilience" in f.details.lower() or "retry" in f.details.lower():
            has_low_resilience = True

    # Check for repeated outbound paths (candidate for caching).
    for call in bp.outbound_calls:
        key = f"{call.method} {call.path}"
        seen_paths[key] = seen_paths.get(key, 0) + 1

    has_repeated_calls = any(v > 1 for v in seen_paths.values())

    # Check for missing retry config on outbound calls.
    calls_without_retry = [c for c in bp.outbound_calls if not c.retry_config]
    if calls_without_retry:
        has_low_resilience = True

    # Check for missing connection pool (heuristic: raw http usage).
    has_raw_client = not bp.retry_configs  # proxy for "no pool configured"

    # --- Emit applicable optimizations ---

    if has_low_resilience:
        code = generate_optimization_code("retry", lang, bp.name)
        results.append((
            "retry",
            code,
            f"Add retry wrapper with exponential backoff for {bp.name} "
            f"({len(calls_without_retry)} unprotected outbound calls)",
        ))

        code = generate_optimization_code("circuit_breaker", lang, bp.name)
        results.append((
            "circuit_breaker",
            code,
            f"Add circuit breaker to prevent {bp.name} from cascading "
            "failures when downstream services are down",
        ))

    if has_timeout_issue:
        code = generate_optimization_code("timeout", lang, bp.name)
        results.append((
            "timeout",
            code,
            f"Add explicit timeout wrapper for {bp.name} outbound HTTP calls",
        ))

    if has_repeated_calls:
        code = generate_optimization_code("response_cache", lang, bp.name)
        repeated = [p for p, c in seen_paths.items() if c > 1]
        results.append((
            "response_cache",
            code,
            f"Add response cache for {bp.name} repeated calls: "
            + ", ".join(repeated),
        ))

    if has_raw_client and bp.outbound_calls:
        code = generate_optimization_code("connection_pool", lang, bp.name)
        results.append((
            "connection_pool",
            code,
            f"Add connection pool for {bp.name} "
            f"({len(bp.outbound_calls)} outbound calls)",
        ))

    return results


def format_codegen_report(
    optimizations: dict[str, list[tuple[str, str, str]]],
) -> str:
    """Format generated code as a markdown report with copy-paste blocks.

    Args:
        optimizations: Mapping of ``service_name`` to the list returned by
            :func:`generate_optimizations_for_service`.

    Returns:
        Markdown string grouped by service.
    """
    if not optimizations:
        return "No optimization code generated.\n"

    total = sum(len(opts) for opts in optimizations.values())
    lines = [f"## Generated Optimization Code ({total} blocks)\n"]

    for service, opts in sorted(optimizations.items()):
        if not opts:
            continue
        lines.append(f"### {service}\n")
        for opt_type, code, description in opts:
            lines.append(f"**{opt_type.replace('_', ' ').title()}** -- {description}\n")
            # Detect language from the code content for syntax highlighting.
            lang_hint = _detect_lang_hint(code)
            lines.append(f"```{lang_hint}")
            lines.append(code.rstrip())
            lines.append("```\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _detect_lang_hint(code: str) -> str:
    """Return a markdown syntax-highlight hint from the code content."""
    if code.lstrip().startswith("//") and "func " in code:
        return "go"
    if code.lstrip().startswith("//") and ("fn " in code or "struct " in code):
        if "reqwest" in code or "tokio" in code or "impl " in code or "Mutex" in code:
            return "rust"
    if code.lstrip().startswith("#") or "def " in code or "class " in code:
        return "python"
    if "async function" in code or "class " in code and "Promise" in code:
        return "typescript"
    if "import {" in code or "new Agent" in code:
        return "typescript"
    if "func " in code:
        return "go"
    if "fn " in code:
        return "rust"
    return ""
